Task 4
kabernardes/log-parser pull request #4
Opened 2022-01-24 17:02 UTC by kabernardes

Log Parser Challenge

Task 4:

1. Count the number of kills per player.
2. Total game kill count.

2022-01-26 18:17 UTC, iagodahlem requested changes

2022-01-26 18:17 UTC, iagodahlem commented on lib/log_parser.rb
> +      end
Isso pode ser feito com um `reduce` também pra ficar mais elegante e menos verboso.

https://medium.com/@james.a.hughes/using-the-reduce-method-in-ruby-907f3c18ae1f
https://apidock.com/ruby/Enumerable/reduce

Também caso tu fosse seguir com o for, um `each` seria mais apropriado pra evitar ter que decrementar `-1` da range.

De qualquer forma, usando `reduce` ou `each`, talvez não seja necessário a chamada de `kills_count` aqui.

2022-01-26 18:17 UTC, iagodahlem commented on lib/log_parser.rb
> +      return players_hash
Aqui pra evitar dois `for`'s, tu pode usar um `map`, ele é bem util pra esses casos onde tu precisa iterar sobre um array e retornar um array novo ou nesse caso, um hash novo.

https://apidock.com/ruby/Enumerable/map

Usando o map talvez nem seja necessário chamar o `finding_players` aqui.

2022-01-26 20:40 UTC, kabernardes commented on lib/log_parser.rb
> +      return players_hash
Iago, já fiz todas as alterações, obrigada! Somente essa que eu não consegui! Eu sou noob no Ruby, se a pergunta for boba, me perdoe! Seguinte: no link que você me mandou, estava dizendo que não era possível alterar o valor das values de um hash com o map, que é o que eu estou tentando fazer no primeiro for. Eu vi uma outra forma, com o .each:
  (0..players_name.length - 1).each do |i|
      players_hash[players_name[i].to_s] = 0
    end
Assim funcionou, acha que fica melhor ou acha que tem outra forma melhor de fazer? Desde já, muito obrigada!

2022-01-27 12:34 UTC, iagodahlem requested changes

2022-01-27 12:34 UTC, iagodahlem commented on lib/log_parser.rb
> +    def kills_count
Aqui o `kills_count` ficou um fora de indentação seguindo o método `finding_players` em cima.

2022-01-27 12:34 UTC, iagodahlem commented on lib/log_parser.rb
> +      players_hash = {}
Eu chamaria essa variável de `kills_hash` ou até `kills_by_players`, pra não confundir com a `@players_hash`.

2022-01-27 12:34 UTC, iagodahlem commented on lib/log_parser.rb
> +    end
Boa, ficou muito melhor com `.each`.

2022-01-27 12:34 UTC, iagodahlem commented on lib/log_parser.rb
> +      for i in 0..@file_data.length-1 do
Como o `@file_data` é um array, tu pode usar `.each` nele também sem precisar usar o `for` montando essa range:

```
      @file_data.each do |line|
```

Ai em vez de acessar a linha como `current_line = @file_data[i]` dentro do loop, tu pode só usar o parâmetro `line` do each.

2022-01-27 12:34 UTC, iagodahlem commented on lib/log_parser.rb
> +    end
Hashs em ruby também aceitam o método each, então tu pode fazer o each diretamente no `@players_hash` (como tu não faz nenhum assign nele, essa variável não vai ser alterada), sem precisar montar a range:

```rb
@players_hash.each do |player|
	players_hash[player.to_s] = 0
end
```

Edit: o `@players_hash` na verdade é um array também né? 🤔  Acho que pra ficar mais claro da pra renomear essa variável pra apenas `@players`.

2022-01-28 12:19 UTC, iagodahlem requested changes

2022-01-28 12:19 UTC, iagodahlem commented on lib/log_parser.rb
> +          player_1 = current_line.split("killed")[0].split(":").last.strip
Pode usar diretamente o `line`, nem precisa dessa variável auxiliar não:

```suggestion
          player_1 = line.split("killed")[0].split(":").last.strip
```

2022-01-28 12:19 UTC, iagodahlem commented on lib/log_parser.rb
> +    end
Aqui ficou um pouco fora de indentação ainda.

2022-01-28 12:19 UTC, iagodahlem commented on lib/log_parser.rb
> +    return kills_hash
Acabei esquecendo de comentar antes, mas não precisa usar `return` explicito em Ruby, por default Ruby sempre vai retornar a ultima linha do método.
```suggestion
    kills_hash
```

2022-01-28 20:46 UTC, iagodahlem approved these changes
LGTM! 👍

2022-01-31 12:01 UTC, closed without merging